# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        feest_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            provider: feest_db_provider

            form_login:
                login_path: /account/login
                check_path: /account/login
                username_parameter: form[username]
                password_parameter: form[password]
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   /logout
                target: /

    access_control:
        #Allow users to register
        - { path: ^/account/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Allow users to log in
        - { path: ^/account/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Disallow access to all other account pages
        - { path: ^/account, roles: ROLE_USER }
        #Allow users to view all events 
        - { path: ^/events/allEvents, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Allow access to event detail
        - { path: ^/events/event_detail/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Disallow access to change events
        - { path: ^/events, roles: ROLE_USER }
        #Allow access to order
        - { path: ^/order, roles: ROLE_USER }
        #Allow access to done (order)
        - { path: ^/done, roles: ROLE_USER }
        #Allow access to done (order)
        - { path: ^/tickets, roles: ROLE_USER }
        
    