# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            http_basic: ~

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        #Disallow access to all other account pages
        - { path: ^/account, roles: ROLE_USER }
        #Allow users to view all events 
        - { path: ^/events/allEvents, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Allow access to event detail
        - { path: ^/events/event_detail/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Disallow access to change events
        - { path: ^/events, roles: ROLE_USER }
        #Allow access to order
        - { path: ^/order, roles: ROLE_USER }
        #Allow access to done (order)
        - { path: ^/done, roles: ROLE_USER }
        #Allow access to done (order)
        - { path: ^/tickets, roles: ROLE_USER }
        
    