<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{

    public function findIfPersonHasTicket($event_id, $user_id) {

        $parameters = array(
            'userid' =>  $user_id,
            'eventid' => $event_id
        );

       $query = $this->getEntityManager()->createQuery("SELECT t FROM AppBundle:Ticket as t where t.owner = :userid AND t.event = :eventid")->setParameters($parameters);

        return $query->getOneOrNullResult();
    }

}
