<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{

    public function findIfPersonHasTicket($event_id, $user_id) {
        return $this->getEntityManager()->createQuery(
            //niet native -> vandaar owner = $user_id -> vertaald naar SQL
            "SELECT t FROM AppBundle:Ticket as t where t.owner = ". $user_id . " AND t.event = " . $event_id
        )->getOneOrNullResult();
    }

}
